ERM-13659. Фикс бага в учёте свойства "Контролируется количеством"
2gis/nuclear-river-validation-rules pull request #442
Opened 2020-11-06 10:49 UTC by maximpashuk

Раньше у нас были номенклатуры, контролирующиеся количеством, только с единичным объектом привязки.
Сейчас появились такие номенклатуры со множественными объектами привязки.

2020-11-09 02:59 UTC, rechkalov commented on src/ValidationRules.Replication/PriceRules/Aggregates/OrderAggregateRootActor.cs
> +                    }).Distinct();
Мне кажется, Distinct и изменение ключа нарушает суть этой проверки - ты больше не знаешь, сколько позиций точно продано и не можешь посчитать их количество.

2020-11-09 03:59 UTC, maximpashuk commented on src/ValidationRules.Replication/PriceRules/Aggregates/OrderAggregateRootActor.cs
> +                    }).Distinct();
Да, ты прав, я что-то вечером в пятницу уже не соображал.

Я сам же в позапрошлом изменении и добавил OrderPositionId, а в пятницу не понял зачем.

2020-11-09 03:59 UTC, maximpashuk commented on src/ValidationRules.Replication/PriceRules/Aggregates/OrderAggregateRootActor.cs
> +                    }).Distinct();
Доеду до работы поправлю

2020-11-11 04:02 UTC, rechkalov requested changes

2020-11-11 04:02 UTC, rechkalov commented on src/ValidationRules.Replication/PriceRules/Aggregates/OrderAggregateRootActor.cs
> +                    }).Distinct();
Но ведь это не будет работать, у тебя дубли ключа (OrderId, OrderPositionId) сохраняются? 

И ты оставил Distinct, разве это не противоречит смыслу проверки? Если в одном заказе в одной позиции есть два РМ с одной категорией (номенклатурной?) - они ведь должны считаться за две, а не за одну?

2020-11-12 05:35 UTC, maximpashuk commented on src/ValidationRules.Replication/PriceRules/Aggregates/OrderAggregateRootActor.cs
> +                    }).Distinct();
Нет, учёт по объектам привязки не ведётся, я уточнял.
Сколько бы ни было объектов привязки, считается за 1.

2020-11-12 05:52 UTC, rechkalov approved these changes

2020-11-13 09:02 UTC, merged